### ISSUE TITLE
extractunikmers.sh lower and upper windows

### ISSUE THREAD

**Issue by rsandean** [sakshar/rambler#3]
Hi, I have ran the extractunikmers.sh and acquired an excel file. I calculated lower and upper window based on the second column of the excel file. I got values of -253234 and 256515, however I get an error when I put in a negative number and when I remove the negative sign I don't get any unikmers extracted. I was wondering if this is the correct way to calculate the lower and upper windows? 

Thank you!

**Comment by sakshar** [comment]
Hello, thanks for reaching out.

Yes, the values cannot be negative. Also, from the values you mentioned here, it seems like there might be something wrong in the way you are calculating the mean and the standard deviation which ultimately gives you the lower (mean - 3*sd) and the upper (mean + 3*sd) bounds on the window.

Just to add, while calculating for the mean and the standard deviation from the excel file, please ignore the first 5 rows (which are mostly k-mers due to sequencing errors) and also ignore the k-mers that appear way higher than the expected coverage depth (suppose, if the expected coverage depth is 100x, ignore rows after row 250). For example, with a read set having a coverage depth of 100x, try to calculate the mean and the standard deviation with values from rows 6 to 250. This is a trick required to discard k-mers coming from sequencing errors and the k-mers which appear way higher than expected that can throw the values of mean and standard deviation way off.

Hope, this helps.

**Comment by sakshar** [comment]
Hi, I have updated the extractUnikmers.sh script. Now, the complete process of extracting unikmers is fully automated and this will generate the list of unikmers without any manual intervention. Hope this helps.

**Comment by rsandean** [comment]
Hi, thank you very much, I will download the new one :)
